# Generated by Django 4.1.2 on 2022-11-19 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(blank=True, max_length=100)),
                ('target_word', models.CharField(blank=True, max_length=100)),
                ('wordcollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordstock.wordcollection')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_synonym', models.CharField(blank=True, max_length=100)),
                ('target_synonym', models.CharField(blank=True, max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordstock.word')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_example', models.CharField(blank=True, max_length=500)),
                ('target_example', models.CharField(blank=True, max_length=500)),
                ('synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordstock.synonym')),
            ],
        ),
    ]
