# Generated by Django 4.1.2 on 2022-12-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordcollection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='example',
            name='synonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='wordstock.synonym'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='wordstock.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='wordcollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordstock.wordcollection'),
        ),
    ]
